Adding in migration squashing template
Medology/.github pull request #45
Opened 2020-12-08 21:41 UTC by BKorenek

This is a PR to add a template for migration squashing.

2020-12-09 12:43 UTC, rashidsaf requested changes

2020-12-09 12:43 UTC, rashidsaf commented on .github/ISSUE_TEMPLATE/Standard-Migration-Squashing-Template.md
> +
```suggestion
Update `InitialDatabaseSchema::MOST_RECENT_MIGRATION_NAME` to the latest migration name on production DB
Update the date on the file name of `yyyy_mm_dd_000000_initial_database_schema.php` 

```

2020-12-09 12:43 UTC, rashidsaf commented on .github/ISSUE_TEMPLATE/Standard-Migration-Squashing-Template.md
> +
```suggestion
- [ ] Latest migration should be updated on the codebase
- [ ] The init_schema file should be renamed to reflect today's date
- [ ] Most recent production DB  schema dump and the local DB schema should be exactly the same after squash

```

2020-12-09 15:28 UTC, Chekote requested changes

2020-12-09 15:28 UTC, Chekote commented on .github/ISSUE_TEMPLATE/Standard-Migration-Squashing-Template.md
> +- [ ] All migrations created prior to the creation of this issue are squashed down into the initial_migration folder.
```suggestion
- [ ] Production schema is NOT modified in any way
- [ ] Production migrations table is updated to reflect this new, single flattened migration
```

2020-12-09 15:28 UTC, Chekote commented on .github/ISSUE_TEMPLATE/Standard-Migration-Squashing-Template.md
> +devchat: All migrations have been squashed, please rebase to master to have a consistent project initialization.
Rebase or merge. Devs should not rebase after code review has began.

2020-12-09 15:47 UTC, PayneWheat requested changes
I haven't squashed the migrations before, but looks like Rashid and Donald suggested some valuable info.

2020-12-10 14:52 UTC, rashidsaf approved these changes

2020-12-10 15:39 UTC, Chekote approved these changes

2020-12-14 15:39 UTC, PayneWheat approved these changes

2020-12-15 15:09 UTC, merged